#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# https://github.com/lemofire/AutoDailyCP
# Lisence: MIT
# Author: 柠火
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-


name: AutoDailyCP

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: 0 8,14,20,24 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
      - name: Download DailyCP
        run: |
          git clone https://gitee.com/helianchichi/FuckDailyCP
          mv ./FuckDailyCP/* ./
      - name: Install extensions
        run: |
          pip3 install setuptools
          pip3 install -r requirements.txt
      - name: DIY formdb
        run: |
          # 请根据日志提示的文件名修改此段代码
          cat>formdb/37.json<<EOF
          [


    {
        "wid": "3132",
        "formWid": "174",
        "fieldType": 2,
        "title": "当前所在地",
        "description": "",
        "minLength": 0,
        "sort": "1",
        "maxLength": null,
        "isRequired": 1,
        "imageCount": null,
        "hasOtherItems": 0,
        "colName": "field001",
        "value": "",
        "minValue": 0.0,
        "maxValue": 0.0,
        "isDecimal": true,
        "fieldItems": [
            {
                "itemWid": "6100",
                "content": "内地",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": 1
            },
            {
                "itemWid": "6101",
                "content": "香港",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6102",
                "content": "澳门",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6103",
                "content": "台湾",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6104",
                "content": "国外",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
        ]
    },
    {
        "wid": "3133",
        "formWid": "174",
        "fieldType": 2,
        "title": "是否在校",
        "description": "",
        "minLength": 0,
        "sort": "2",
        "maxLength": null,
        "isRequired": 1,
        "imageCount": null,
        "hasOtherItems": 0,
        "colName": "field002",
        "value": "",
        "minValue": 0.0,
        "maxValue": 0.0,
        "isDecimal": true,
        "fieldItems": [
            {
                "itemWid": "6105",
                "content": "东区",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6106",
                "content": "南区",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6107",
                "content": "中区",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6108",
                "content": "北区",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6109",
                "content": "西区",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": 1
            },
            {
                "itemWid": "6110",
                "content": "校外",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            }
        ]
    },
    {
        "wid": "3134",
        "formWid": "174",
        "fieldType": 2,
        "title": "当前身体状况",
        "description": "",
        "minLength": 0,
        "sort": "3",
        "maxLength": null,
        "isRequired": 1,
        "imageCount": null,
        "hasOtherItems": 0,
        "colName": "field003",
        "value": "",
        "minValue": 0.0,
        "maxValue": 0.0,
        "isDecimal": true,
        "fieldItems": [
            {
                "itemWid": "6111",
                "content": "-请选择-",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6112",
                "content": "正常",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": 1
            },
            {
                "itemWid": "6113",
                "content": "疑似",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6114",
                "content": "确诊",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6115",
                "content": "其他",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            }
        ]
    },
    {
        "wid": "3135",
        "formWid": "174",
        "fieldType": 2,
        "title": "当前状态",
        "description": "",
        "minLength": 0,
        "sort": "4",
        "maxLength": null,
        "isRequired": 1,
        "imageCount": null,
        "hasOtherItems": 0,
        "colName": "field004",
        "value": "",
        "minValue": 0.0,
        "maxValue": 0.0,
        "isDecimal": true,
        "fieldItems": [
            {
                "itemWid": "6116",
                "content": "-请选择-",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6117",
                "content": "正常在校园内",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": 1
            },
            {
                "itemWid": "6118",
                "content": "正常在家",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6119",
                "content": "居家留观",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6120",
                "content": "集中留观",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6121",
                "content": "住院治疗",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6122",
                "content": "其他",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            }
        ]
    },
    {
        "wid": "3136",
        "formWid": "174",
        "fieldType": 2,
        "title": "目前有无发热症状",
        "description": "",
        "minLength": 0,
        "sort": "5",
        "maxLength": null,
        "isRequired": 1,
        "imageCount": null,
        "hasOtherItems": 0,
        "colName": "field005",
        "value": "",
        "minValue": 0.0,
        "maxValue": 0.0,
        "isDecimal": true,
        "fieldItems": [
            {
                "itemWid": "6123",
                "content": "有",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6124",
                "content": "无",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": 1
            }
        ]
    },
    {
        "wid": "3137",
        "formWid": "174",
        "fieldType": 2,
        "title": "自寒假开始后，是否接触过确诊或疑似病例的患者",
        "description": "",
        "minLength": 0,
        "sort": "5",
        "maxLength": null,
        "isRequired": 1,
        "imageCount": null,
        "hasOtherItems": 0,
        "colName": "field005",
        "value": "",
        "minValue": 0.0,
        "maxValue": 0.0,
        "isDecimal": true,
        "fieldItems": [
            {
                "itemWid": "6125",
                "content": "有",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": null
            },
            {
                "itemWid": "6126",
                "content": "无",
                "isOtherItems": 0,
                "contendExtend": null,
                "isSelected": 1
            }
        ]
    }
]
          EOF
      - name: Run program
        env:
          SCHOOL_NAME: ${{ secrets.SCHOOL_NAME }}
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ADDRESS: ${{ secrets.ADDRESS }}
        run: |
          python3 DailyCP.py ${SCHOOL_NAME} ${ACCOUNT} ${PASSWORD} ${ADDRESS}
      - name : Upload formdb
        uses: actions/upload-artifact@master
        with:
          name: formdb
          path: formdb
